name: HypixelSBGrapplingHook
main: me.deemu.grapplinghook.main
version: 1.4
api-version: 1.16
description: GrapplingHook Plugin.

commands:
  grapplinghook:
    aliases:
      - gh
  ghconsolegive:
    description: The command to give players the gh from console

permissions:
  grapplinghook.admin:
    description: The admin perms!
